language: python
python: 3.5
sudo: required
dist: trusty
before_install:
- sudo add-apt-repository -y ppa:ethereumclassic/ethereum
- sudo apt-get update
- sudo apt-get install -y solc
env:
  matrix:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
  global:
    - COVERAGE_APPEND="--append"
    - secure: XXX
install:
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
  - travis_retry pip install coverage
script:
  - if [ -d .tox/$TOX_ENV/ ]; then cd .tox/$TOX_ENV && coverage erase; fi;
  - tox -e $TOX_ENV -- --ignore ethereum/tests/test_vm.py --ignore ethereum/tests/test_state.py
  - tox -e $TOX_ENV -- ethereum/tests/test_vm.py
  - tox -e $TOX_ENV -- ethereum/tests/test_state.py
  - coverage report --show-missing
after_success:
  - travis_retry pip install coveralls
  - cd .tox/$TOX_ENV && coveralls
after_script:
  - cat .tox/$TOX_ENV/log/*.log; true
notifications:
  slack:
    secure: XXX
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: pypi
  user: ethereum_pypi_automated
  password:
    secure: XXX
  on:
    tags: true
    repo: ethereum/pyethereum
    branch: develop
after_deploy:
- ./.release_notify.sh
